# Generated by Django 4.2.2 on 2023-06-19 20:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Shorted URL Hash')),
                ('url', models.URLField(max_length=2048, verbose_name='Target URL')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ('-url', '-id'),
            },
        ),
    ]
